const cssom = {}
cssom.frontCss = function(coverCss = ""){
    let str = ".printFrontPage {background-color: #fff; font-size: 14px; color: #000000;page-break-after:always;}.dataText { display: inline-block; line-height: 20px; min-width: 60px; border-bottom: 1px solid #000000; color: #333333; padding: 0 10px; box-sizing: border-box; } .color666 { color: #333333; } .dataTextSmall { min-width: 30px; } .tableText { border: none; min-width: initial; padding: 0; overflow-wrap: break-word; word-break: break-word; } .firstTitle { text-align: center; position: relative; } .h3 { font-size: 20px; line-height: 1.8; font-weight: 700; color: #000000; } .h4 { line-height: 1.5; font-size: 16px; font-weight: 500; color: #000000; } .organizationalCode { position: absolute; right: 30px; top: 4px; } .medicalRecordOuter { border: 1px solid #000; padding: 20px } .baseInfo { margin-top: 18px; } .baseInfoUp { padding-bottom: 10px; display: box; display: -webkit-box; display: -webkit-flex; display: -moz-box; display: -ms-flexbox; display: flex; justify-content: space-between; } .contentInfo { padding-top: 10px; border: 1px solid #000; } .contentInfoTop { padding: 0 10px; margin-bottom: 10px; display: box; display: -webkit-box; display: -webkit-flex; display: -moz-box; display: -ms-flexbox; display: flex; justify-content: space-between; } .contentInfoTable { display: box; display: -webkit-box; display: -webkit-flex; display: -moz-box; display: -ms-flexbox; display: flex; border-top: 1px solid #000; } .diagnosisRow { display: box; display: -webkit-box; display: -webkit-flex; display: -moz-box; display: -ms-flexbox; display: flex; flex: 0.5; } .contentInfoTableMax { border-right: 1px solid #000; flex: 3; } .contentInfoTableTitle { text-align: center; } .contentInfoTableMid { border-right: 1px solid #000; flex: 1; } .borderBottom { border-bottom: 1px solid #000; } .contentInfoTableMin { border-right: 1px solid #000; flex: 0.5; } .noBorder { border-color: transparent; } .transparentBorder { border-right: 1px solid transparent; } .contentInfoTableAcores { display: box; display: -webkit-box; display: -webkit-flex; display: -moz-box; display: -ms-flexbox; display: flex; border-top: 1px solid #000; justify-content: space-between; } .borderTopNone { border-top: none; } .contentInfoTableHeight { padding-top: 10px; padding-bottom: 10px; line-height: 20px; } .borderColor666 { border-color: #333333; }"
    return str + coverCss;
}
cssom.BackCss = function(coverCss = ""){
    let str = ".printBackPage .flexAlignCenter { display: box; display: -webkit-box; display: -webkit-flex; display: -moz-box; display: -ms-flexbox; display: flex; align-items: center; } .printBackPage .contentInfo { padding-top: 0; } .printBackPage .contentInfoTable { height: 100%; justify-content: space-between; } .printBackPage .contentInfoValue { color: #333333; } .printBackPage .contentInfoTableTitle { padding-top: 10px; } .printBackPage .contentInfoTableMax { flex: 2.4; } .printBackPage .contentInfoTableInnerFlex { display: box; display: -webkit-box; display: -webkit-flex; display: -moz-box; display: -ms-flexbox; display: flex; border-top: 1px solid #000; } .printBackPage .contentInfoTableInnerFlex div { flex: 1; border-right: 1px solid #000; } .printBackPage .contentInfoTableInnerFlex div:nth-child(3) { border-right: none; } .printBackPage .contentInfoTableInnerFlexNoBorderTop { border-top: none; height: 100%; } .printBackPage .contentInfoTableMaxx { border-right: 1px solid #000; flex: 1.5; } .printBackPage .contentInfoTableMidd { border-right: 1px solid #000; flex: 1.4; } .printBackPage .contentInfoTableMin { flex: 0.8; } .printBackPage .noBorder { border-right: none; } .printBackPage .noBorderTop { border-top: none; } .printBackPage .noBorderBottom { padding: 0; vertical-align: baseline; border-bottom: none; }"
    return str + coverCss;
}
export default cssom
